image: alpine:latest

stages:
  - test

variables:
  PYTHONPATH: "$PYTHONPATH:$CI_PROJECT_DIR/src"
  
before_script:
  - apk add --update python3 py3-pip
  - echo "Python 3 installed"
  - pip3 install PyQt5
  - echo "PyQt5 installed"

run-tests:
  tags:
    - docker-runner
  stage: test
  script:
    - python3 -m unittest discover test
  only:
    - merge_requests
    - main
    - dev
    - feature/gui
