name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: python:3.9-slim-buster

    env:
      PYTHONPATH: "$PYTHONPATH:$GITHUB_WORKSPACE/src"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3-pip libgl1-mesa-glx libxcb1 libx11-xcb1 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libfontconfig1 libxcb-util0 wget
          wget http://ftp.us.debian.org/debian/pool/main/x/xcb-util/libxcb-util1_0.4.0-1+b1_amd64.deb
          dpkg -i libxcb-util1_0.4.0-1+b1_amd64.deb
          echo "Installed libxcb-util1"
          pip3 uninstall -y PyQt5
          pip3 install PyQt5
          echo "Python 3, pip, and dependencies installed"

      - name: Run tests
        run: |
          export QT_DEBUG_PLUGINS=1
          export QT_QPA_PLATFORM=offscreen
          python3 -m unittest discover test
